#!/usr/bin/env node
/**
 * Generate a .env with a strong signing key and a first admin password.
 *
 * The two settings the server refuses to start without are both things people
 * get wrong by hand, so they are generated rather than invented.
 */
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const envPath = resolve(process.cwd(), '.env');

/**
 * A .env copied straight from .env.example has the keys but no values, and is
 * unusable. Refusing to touch it leaves the user stuck, so only a .env that
 * actually carries a signing key is treated as one worth protecting.
 */
function isConfigured(path) {
  const match = readFileSync(path, 'utf8').match(/^JWT_SECRET=(.*)$/m);
  return Boolean(match && match[1].trim());
}

if (existsSync(envPath) && isConfigured(envPath) && !process.argv.includes('--force')) {
  console.error(
    `\n.env already exists at ${envPath} and is configured.\n` +
      `Nothing changed — delete it, or re-run with --force, if you really want a new one.\n` +
      `Regenerating JWT_SECRET signs everyone out; regenerating the admin password does\n` +
      `nothing to the account that already exists in the database.\n`,
  );
  process.exit(1);
}

if (existsSync(envPath)) {
  console.log('\nFound a .env with no signing key set — replacing it with a working one.');
}

/** Readable but strong: 4 words' worth of entropy without ambiguous characters. */
function password() {
  const alphabet = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const bytes = randomBytes(20);
  return Array.from(bytes, (b) => alphabet[b % alphabet.length]).join('');
}

const adminEmail = process.env.SEED_ADMIN_EMAIL ?? 'admin@sem.com.au';
const adminPassword = password();

writeFileSync(
  envPath,
  [
    '# Generated by `npm run setup`. Keep this file off version control.',
    '',
    '# Signs session tokens. Changing it signs everyone out.',
    `JWT_SECRET=${randomBytes(32).toString('hex')}`,
    '',
    '# The database file. This is the whole tool - back it up. See `npm run backup`.',
    'DB_PATH=./data/semcom.db',
    '',
    'PORT=4000',
    'NODE_ENV=production',
    '',
    '# The first admin, created only when there are no users yet.',
    `SEED_ADMIN_EMAIL=${adminEmail}`,
    `SEED_ADMIN_PASSWORD=${adminPassword}`,
    '',
  ].join('\n'),
  { mode: 0o600 },
);

console.log(`
Created .env

  Sign in with:  ${adminEmail}
  Password:      ${adminPassword}

Write that password down now — it is stored only in .env, and once the database
is created, changing .env will not change the account.

Next:  npm start
`);
